### ISSUE TITLE
etcd2

### ISSUE THREAD

**Issue by daemonza** [digital-wonderland/docker-elasticsearch#1]
Using this on a etcd 0.4.7 cluster is works as expected. Using this on a etcd 2 cluster, seems to break the cluster for some reason.

**Comment by digital-wonderland** [comment]
This image only accesses etcd via [confd](https://github.com/kelseyhightower/confd). I updated it to the latest version but due to some build issue on docker hub it prolly will take a while until it shows up.

Regardless if this fixes it or not: can you please raise an issue with the etcd guys? Even if 'it doesn't work' it shouldn't be able to break the cluster.
